sudo: false
language: cpp

# Environment variables
env:
  global:
    - PATH: $PATH:$TRAVIS_BUILD_DIR/esp/xtensa-esp32-elf/bin
    - IDF_PATH: $TRAVIS_BUILD_DIR/esp/esp-idf
    - GH_REPO_NAME: esp32-MPU-driver
    - GH_REPO_REF: github.com/natanaeljr/esp32-MPU-driver.git
    - DOXYFILE_PATH: docs/doxygen
    - DOXYFILE: Doxyfile

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - libncurses-dev
      - flex
      - bison
      - gperf
      - python
      - python-serial

# setup to run script
before_script:
  - $TRAVIS_BUILD_DIR/tools/ci/setup_esp_idf.sh
  - $TRAVIS_BUILD_DIR/tools/ci/setup_ext_libs.sh
  - cd $TRAVIS_BUILD_DIR/test/unit-test-app
  - sed -i 's/${HOME}/${TRAVIS_BUILD_DIR}/g' Makefile
  - cat Makefile

# Build code
script:
  # Try build unit-test-app
  - cd $TRAVIS_BUILD_DIR/test/unit-test-app
  - make defconfig
  - make list-components
  - make all -j5


# Generate Doxygen documentation
after_success:
  - $TRAVIS_BUILD_DIR/tools/ci/gen_doxygen_docs.sh

# Deploy docs to gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: gh-pages
  on:
    branch: dev
